// JavaScript Document
var quiz = {
    // Put category here
    multiList: [{
  
    ques: "<strong>Question 1</strong><br/>Katse Dam generates hydro&#8209;electricity. ",
    ans: "True",
    ansSel: ["False"]
}, {
    ques: "<strong>Question 2</strong><br/>Natural gas is piped into Port Nolloth and Mossel Bay.",
    ans: "True",
    ansSel: ["False"]
}, {
    ques: "<strong>Question 3</strong><br/>Natural gas is an example of a renewable energy source. ",
    ans: "False",
    ansSel: ["True"]
}, {
    ques: "<strong>Question 4</strong><br/>Solar and wind are examples of renewable energy sources.",
    ans: "True",
    ansSel: ["False"]
}, {
    ques: "<strong>Question 5</strong><br/>A solar energy project exists near Upington, Northern Cape.",
    ans: "True",
    ansSel: ["False"]
}, {
    ques: "<strong>Question 6</strong><br/>Hydro&#8209;electricity is an example of a non&#8209;renewable energy source.",
    ans: "False",
    ansSel: ["True"]
}, {
    ques: "<strong>Question 7</strong><br/>According to the map of sources of energy, the Eastern Cape has the largest number of hydro&#8209;electricity sites.",
    ans: "True",
    ansSel: ["False"]
}, {
    ques: "<strong>Question 8</strong><br/>Koeberg nuclear power station is situated 50&#160;km north of Cape Town.",
    ans: "True",
    ansSel: ["False"]
}, {
    ques: "<strong>Question 9</strong><br/>The majority of South Africa's energy is generated by nuclear power.",
    ans: "False",
    ansSel: ["True"]
}, {
    ques: "<strong>Question 10</strong><br/>Solar is the most expensive energy source. ",
    ans: "True",
    ansSel: ["False"]
}
        // Copy to hear and remove last comma
    ]
};